//
// Created by axxa on 11/4/20.
//

#ifndef INSTRUMENTASSESSMENTENGINE_ACTUAL_360_H
#define INSTRUMENTASSESSMENTENGINE_ACTUAL_360_H

/*
class Actual_360 {

};
*/

#endif //INSTRUMENTASSESSMENTENGINE_ACTUAL_360_H
